import type { NextPage } from 'next'
import Head from 'next/head'
import NavTab from '@components/NavTab/NavTab'
import BottomTab from '@components/BottomTab/BottomTab'
import QueryTab from '@components/QueryTab/QueryTab'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<NavTab />
			<QueryTab />
			<BottomTab />
		</>
	)
}

export default Home
